from typing import Any, AsyncIterator, Iterator, Mapping, Optional, Sequence, Union

def version() -> str: ...
def override_prompt(name: str, text: str) -> None: ...

class Config:
    @staticmethod
    def default() -> "Config": ...
    @staticmethod
    def from_file(path: str) -> "Config": ...
    @staticmethod
    def from_toml(text: str) -> "Config": ...
    def to_toml(self) -> str: ...

class Budget:
    max_tokens: int
    max_cost_usd: float
    max_wallclock_secs: float
    max_tool_calls: int
    def __init__(
        self,
        max_tokens: int = 50000,
        max_cost_usd: float = 0.5,
        max_wallclock_secs: float = 120.0,
        max_tool_calls: int = 8,
    ) -> None: ...

class Job:
    def progress(self) -> Iterator[dict[str, Any]]: ...
    def wait(self) -> dict[str, Any]: ...
    def cancel(self) -> None: ...

class AskStream:
    def __iter__(self) -> "AskStream": ...
    def __next__(self) -> dict[str, Any]: ...
    def __aiter__(self) -> "AskStream": ...
    def __anext__(self) -> Any: ...
    def collect(self) -> dict[str, Any]: ...

class Index:
    @staticmethod
    def create(path: str, config: Optional[Config] = None) -> "Index": ...
    @staticmethod
    def open(path: str, config: Optional[Config] = None) -> "Index": ...
    def configure(self, config: Config) -> None: ...
    @property
    def path(self) -> str: ...
    def add(
        self,
        source: str,
        policy: Optional[Union[str, Mapping[str, Any]]] = None,
        force: bool = False,
    ) -> Job: ...
    def register_operator(self, op: Any) -> None: ...
    def operators(self) -> list[str]: ...
    def search(
        self,
        query: str,
        k: int = 10,
        videos: Optional[Sequence[str]] = None,
        kinds: Optional[Sequence[str]] = None,
        text_only: bool = False,
    ) -> list[dict[str, Any]]: ...
    def ask(
        self,
        question: str,
        budget: Optional[Budget] = None,
        videos: Optional[Sequence[str]] = None,
        session_id: Optional[str] = None,
        policy: Optional[Union[str, Any]] = None,
        model: Optional[str] = None,
    ) -> AskStream: ...
    def aask(
        self,
        question: str,
        budget: Optional[Budget] = None,
        videos: Optional[Sequence[str]] = None,
        session_id: Optional[str] = None,
        policy: Optional[Union[str, Any]] = None,
        model: Optional[str] = None,
    ) -> AsyncIterator[dict[str, Any]]: ...
    def view(self, video_id: str, t0: float, t1: float, fps: float = 1.0, cols: int = 3) -> dict[str, Any]: ...
    def frame(self, video_id: str, t: float, max_dim: int = 640) -> Any: ...
    def timeline(self, video_id: str, level: str = "chapter") -> list[dict[str, Any]]: ...
    def videos(self) -> list[dict[str, Any]]: ...
    def status(self) -> dict[str, Any]: ...
