[package]
name = "vi-index"
description = "VideoIndex vi-index (in progress)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
vi-core = { workspace = true }

[lints]
workspace = true
