//! Fixtures for VideoIndex tests. The fixture video is generated by
//! `build.rs` with ffmpeg at build time, so `cargo test` needs no network.
//!
//! Layout of the fixture (see `build.rs`): 120 s, 640x360, 30 fps, twelve
//! 10-second segments with hard cuts, each a distinct solid colour with a
//! white box at a per-segment position, timestamp text top-right, 440 Hz tone.

#![cfg_attr(test, allow(clippy::unwrap_used))]

use std::path::PathBuf;

/// Total duration in seconds.
pub const DURATION_SECS: f64 = 120.0;
/// Seconds per segment (hard cut every this many seconds).
pub const SEGMENT_SECS: f64 = 10.0;
/// Frame width.
pub const WIDTH: u32 = 640;
/// Frame height.
pub const HEIGHT: u32 = 360;
/// Frame rate.
pub const FPS: f64 = 30.0;
/// Audio sample rate of the source.
pub const AUDIO_RATE: u32 = 48_000;
/// Tone frequency.
pub const TONE_HZ: f64 = 440.0;

/// Background colour of each segment, RGB. Mirrors `build.rs`.
pub const SEGMENT_COLORS: [[u8; 3]; 12] = [
    [0xC0, 0x30, 0x30],
    [0x30, 0xA0, 0x30],
    [0x30, 0x30, 0xC0],
    [0xC0, 0xC0, 0x30],
    [0xC0, 0x30, 0xC0],
    [0x30, 0xC0, 0xC0],
    [0xE0, 0x80, 0x20],
    [0x70, 0x30, 0xA0],
    [0x20, 0x80, 0x70],
    [0x80, 0x50, 0x20],
    [0xE0, 0x80, 0xA0],
    [0x80, 0x80, 0x80],
];

/// Path of the generated fixture.
pub fn fixture_path() -> PathBuf {
    PathBuf::from(env!("VI_FIXTURE_PATH"))
}

/// Segment index for a time.
pub fn segment_at(t_secs: f64) -> usize {
    ((t_secs / SEGMENT_SECS).floor() as usize).min(SEGMENT_COLORS.len() - 1)
}

/// Expected background colour at a time.
pub fn color_at(t_secs: f64) -> [u8; 3] {
    SEGMENT_COLORS[segment_at(t_secs)]
}

/// A pixel that is background in every segment (outside every box and the
/// timestamp text), in fixture coordinates. Scale by `w / WIDTH` for scaled
/// frames.
pub const BACKGROUND_PROBE_XY: (u32, u32) = (20, 350);

/// True when `actual` is within `tol` of `expected` on every channel; colour
/// conversion through yuv420p costs a few units.
pub fn color_close(actual: [u8; 3], expected: [u8; 3], tol: u8) -> bool {
    actual
        .iter()
        .zip(expected.iter())
        .all(|(a, e)| (i16::from(*a) - i16::from(*e)).abs() <= i16::from(tol))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixture_exists() {
        let p = fixture_path();
        assert!(p.is_file(), "missing {}", p.display());
        assert!(std::fs::metadata(&p).unwrap().len() > 10_000);
    }

    #[test]
    fn segments() {
        assert_eq!(segment_at(0.0), 0);
        assert_eq!(segment_at(9.99), 0);
        assert_eq!(segment_at(10.0), 1);
        assert_eq!(segment_at(119.9), 11);
        assert_eq!(segment_at(500.0), 11);
    }
}
